#!/bin/bash

#Custermize this for your application
APPLICATION_FILE_PATH=jackdmp
ERR=/tmp/remove_JackInstaller_log

#Parameters
PRODUCT_HOME=/Library/__PRODUCT__/__VERSION__
ERR=/tmp/

echo "Post installation process started"

#Change permissions in home directory
echo "Change permissions in product home"
cd ${PRODUCT_HOME}
chmod -R 755 .
[ -d /usr/local/bin ] || mkdir /usr/local/bin


# create symlink for each application file
for filename in ${PRODUCT_HOME}; do
    ln -s ${PRODUCT_HOME}/${filename} /usr/local/bin/${filename} 2>>$ERR
done

#Add application shortcut to /usr/local/bin
#rm -f /usr/local/bin/__PRODUCT__-__VERSION__
#ln -s ${PRODUCT_HOME}/${APPLICATION_FILE_PATH} /usr/local/bin/__PRODUCT__-__VERSION__
echo "Post installation process finished"
