#!/bin/bash

ERR=/tmp/install_Jacktrip_log

#Parameters
PRODUCT_HOME=/Library/__PRODUCT__/__VERSION__

echo "Post installation process started"

#Change permissions in home directory
echo "Change permissions in product home"
cd ${PRODUCT_HOME}
chmod -R 755 .
[ -d /usr/local/bin ] || mkdir /usr/local/bin

# create symlink for each application file
for filename in ${PRODUCT_HOME}/jack2_binaries; do
    ln -s ${PRODUCT_HOME}/${filename} /usr/local/bin/${filename} 2>>$ERR
done

sudo mv -f QjackCtl.app /Applications

echo "Post installation process finished"
